# Generated by Django 5.2.7 on 2026-04-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_project_b78682_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_priorit_a900d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_assigne_a1ddb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_deadlin_736196_idx',
        ),
    ]
